spring.application.name=backend

spring.datasource.url=jdbc:oracle:thin:@//127.0.0.1:1522/XEPDB1
spring.datasource.username=TEAM1
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.ffg.backend